### ISSUE TITLE
Error orientation of screenshot

### ISSUE THREAD

**Issue by NakanoSanku** [rayworks/DroidCast#15]
![image](https://github.com/rayworks/DroidCast/assets/96334375/2e57bf04-9188-485b-8f22-6efb83276abe)
Device :mumu12
sdk:32
abi:x86_64
GPU:RX6600 
Driver version: 23.8.1

**Comment by rayworks** [comment]
Hi @NakanoSanku, you could try with another script (`python3 scripts/screencap_server.py`) under the same folder as long as you have `adb` installed.

Open url `http://localhost:12347/screenshot` in browser, you should see the screenshot.

**Comment by rayworks** [comment]
Please try with the latest version.
Fixed on commit : 2554171

**Comment by NakanoSanku** [comment]
> Please try with the latest version.
> Fixed on commit : 2554171

so cool !

**Comment by rayworks** [comment]
> > Please try with the latest version.
> > Fixed on commit : [2554171](https://github.com/rayworks/DroidCast/commit/2554171c45345559b87d50f8f67f68301c4e79b6)
> 
> so cool !

Thanks, please also consider starring the repo.

**Comment by fj3224013877** [comment]
更换模拟器截屏方案就可以了，我也是什么界面都识别不了，
