### ISSUE TITLE
Frequent usage of /screenshot endpoint causes memory problem

### ISSUE THREAD

**Issue by rdmrtn** [rayworks/DroidCast#18]
For Android 14, if /screenshot endpoint is called frequently via curl command in a loop, high memory usage occurs.

**Comment by rayworks** [comment]
Hi @rdmrtn ,

IMO, It sort of depends on the frequency of calling `screenshot` in your case. As you can see, the bitmap will be generated [at here](https://github.com/rayworks/DroidCast/blob/master/app/src/main/java/com/rayworks/droidcast/ScreenCaptorUtils.java#L85) .  However in Java world, these bitmap objects should be taken care of by GC, even I invoke `bitmap.recycle()` to free the native object associated with this bitmap, and clear the reference to the pixel data. This will not free the pixel data synchronously.

If there is more context / profile data you can share, that will be more helpful to dig deep.

**Comment by rdmrtn** [comment]
Hi,

When I start to fetch screenshots via curl, memory usage increases as below. When I stop fetching screenshots, increasing stops but stays at same level. The memory is not released until I kill the process in phone.
![Screenshot from 2023-11-30 09-45-45](https://github.com/rayworks/DroidCast/assets/1902724/e1dbbc1c-8e86-4389-b464-dd88cd9dac41)


Actually, I suspect from [here](https://github.com/rayworks/DroidCast/blob/5c1418b116a4bc9e80ceefe454d7c92c51c10407/app/src/main/java/com/rayworks/droidcast/Main.java#L205).

When I commented this line, there is not any memory usage stays constant.

**Comment by rayworks** [comment]
@rdmrtn , thank you for the detail info.
I've made a new build  (DroidCast-debug-1.2.0-1130.apk) and uploaded to wetransfer : https://we.tl/t-ExNIgLFIYX
Feel free to test again it, however, I can only get an emulator to test.

Related changes :
<img width="1042" alt="Screenshot 2023-11-30 at 22 45 36" src="https://github.com/rayworks/DroidCast/assets/1329281/afa0aa2c-bbf7-4769-a93a-784170c5be35">

**Comment by rayworks** [comment]
We do need a way to convert the bitmap to raw bytes and transmit them. So the compress method is required. 

One more question, can you keep running it and monitor the OOM error in the end?

**Comment by rdmrtn** [comment]
Emulator causes my PC to be frozen.

**Comment by rayworks** [comment]
```
$ adb shell ps -ef | grep -i cast
shell         9709  6847 0 15:59:31 ?     00:00:00 sh -c CLASSPATH=/data/app/~~_UuZ-rloyCdtyK-KN92wrQ==/com.rayworks.droidcast-jlhSVZxbO1yPkfywjq_D_w==/base.apk app_process / com.rayworks.droidcast.Main --port=53516
shell         9711  9709 1 15:59:31 ?     00:00:13 app_process / com.rayworks.droidcast.Main --port=53516
```
9711 is the retrieved process on my machine.

```
adb shell dumpsys meminfo 9711
``` 

You can run above commands to dump memory info for the target running process.
There is a change between taking screenshots and after for the same process.

<img width="951" alt="before" src="https://github.com/rayworks/DroidCast/assets/1329281/b92917d2-4319-40e6-80ae-d108be6bd254">

<img width="935" alt="after" src="https://github.com/rayworks/DroidCast/assets/1329281/5ba463c4-a2b4-4e7d-8fb6-8f33bde3d644">

**Comment by rdmrtn** [comment]
Even if my android sdk 34 emulator causes OOM, for a real device everything seems to be okay. Thank you for your interest.
